<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
?>

<meta type="page" content="purchase_view"/>

<?php
$metaTag = '<meta name="product:product_id" content="%s" />';
$order = Mage::getSingleton('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId());
$items = $order->getAllItems();
$productsList = array();

foreach ($items as $item) {
    $parentId = null;
    $productId = $item->getProductId();
    //Receives parent ID, if exists
    $parentProducts = Mage::getResourceSingleton('catalog/product_type_configurable')
        ->getParentIdsByChild($productId);

    if ($parentProducts != null) {
        $parentId = $parentProducts[0];
    }
    //Checks if exists parent product, if exists, add parent ID in array, case not, then add simple product ID in array
    if ($parentId != null && !$productsList[$parentId]) {
        $productsList[$parentId] = $parentId;
        echo sprintf($metaTag, $parentProducts[0]);
    } elseif (!$productsList[$parentId]) {
        $productsList[$productId] = $productId;
        echo sprintf($metaTag, $productId);
    }
}
?>
