<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
?>

<meta type="page" content="purchase_view"/>

<?php
$meta_tag = '<meta name="product:product_id" content="%s" />';
$items = Mage::getModel('checkout/cart')->getQuote()->getAllItems();

foreach ($items as item) {
    $value = $product->getId();
    echo sprintf($meta_tag, $value);
}
?>
