<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
//Get current product
$product = Mage::registry('current_product');
$allCategories = Mage::helper('prognoos')->getAllCategoriesByProduct($product->getCategoryCollection());
?>

<meta type="page" content="product_view"/>
<!-- Para tracking de atributos de produto - OBRIGATORIOS -->
<meta name="product:product_id" content="<?php echo $product->getId() ?>"/>
<meta name="product:category" content="<?php echo $allCategories ?>"/>
<meta name="product:product_name" content="<?php echo $product->getShortDescription() ?>"/>
<meta name="product:product_url" content="<?php echo $product->getUrl() ?>"/>
<meta name="product:product_img_url" content="<?php echo $product->getImageUrl() ?>"/>
<meta name="product:price" content="<?php echo $product->getPrice() ?>"/>
<meta name="product:priceSell" content="<?php echo $product->getPrice() ?>"/>

<?php

$meta_tag = '<meta name="product:%s" content="%s" />';
$attributes_str = "";

function IsNullOrEmptyString($value){
    return (!isset($value) || trim($value)==='');
}

foreach (explode(",", $attributes_str) as $attr) {
    $value = $product->getData();

    if (!IsNullOrEmptyString($value)) {
        echo sprintf($meta_tag, $attr, $product->getData($attr));
    }
}
?>

