<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
$urlSite = Mage::getStoreConfig('geral/geral/url_site');
?>

<div class="showcase"></div>

<script type="text/javascript">
    var product_template = '<div><h2><a href="##URL#">##NAME##<\/a><\/h2><div><img src="##IMG##"><\/div><\/div>';

    function exibeRecs(recommendations) {
        var di = document.getElementById('showcase');
        var elements_html = "";

        for (var i = 0; i < 5; i++) {
            var new_html = product_template.replace('##NAME##', recommendations[i].data_product_name);
            new_html = new_html.replace('##URL##', recommendations[i].data_product_url);
            new_html = new_html.replace('##IMG##', location.protocol + recommendations[i].data_product_img_url);
            elements_html += new_html;
        }
        di.innerHTML = elements_html;
    }
</script>


<script type="text/javascript"
        src="https://cariri.prognoos.com/heuristic?cid=<?php echo $urlSite ?>&heuristic=top_visited&jsonp=exibeRecs">