<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
$blockInfo = $this->getData();
$maxQtyProductsShowcase = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/qty_recommended');
$showcaseTitle = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/title_recommended_showcase');
$prognoosHelper = Mage::helper('prognoos');
$templateEnabled = $prognoosHelper->getTemplate($blockInfo['page_name'], $blockInfo['showcase_type']);
$prognoosUser = $prognoosHelper->getPrognoosUser();
?>

<?php if ($templateEnabled): ?>
    <!-- Showcase - Recommended for you -->
    <div id="prognoos_ub_showcase"></div>

    <div id="prognoos_product_style1_line" style="display:none;">
        <div class="widget widget-new-products">
            <div class="widget-title">
                <h2>##TITLE##</h2>
            </div>
            <div class="widget-products">
                <ul id="recommended-showcase"
                    class="products-grid products-grid--max-<?php echo $maxQtyProductsShowcase ?>-col-widget">##INNER##</ul>
            </div>
        </div>
    </div>
    <div id="prognoos_product_style1" style="display:none;">
        <?php echo preg_replace('/\s+/', ' ',
            trim(Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/layout_recommended')))?>
    </div>

    <script>
    PrognoosFacade.ubased("<?php echo $prognoosUser ?>", <?php echo $maxQtyProductsShowcase ?>);
    </script>

<?php endif; ?>
