<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
$blockInfo = $this->getData();
$maxQtyProductsShowcase = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/qty_recommended');
$prognoosHelper = Mage::helper('prognoos');
$templateEnabled = $prognoosHelper->getTemplate($blockInfo['page_name'], $blockInfo['showcase_type']);
$prognoosUser = $prognoosHelper->getPrognoosUser();
?>

<?php if ($templateEnabled): ?>

    <script>

        var product_template = '<?php echo preg_replace('/\s+/', ' ',
            trim(Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/layout_recommended')))?>';

        function exibeRecsGeneral(recommendations) {
            var di = document.getElementById('recommended-showcase');
            var elements_html = "";

            for (var i = 0; i < <?php echo $maxQtyProductsShowcase ?>; i++) {

                var new_html = product_template.replace(/##NAME##/g, recommendations[i].name);
                new_html = new_html.replace(/##URL##/g, recommendations[i].url);
                new_html = new_html.replace(/##IMG##/g, location.protocol + recommendations[i].img_url);
                new_html = new_html.replace(/##PRICE##/g, 'R$' + recommendations[i].price);
                elements_html += new_html;
            }
            di.innerHTML = elements_html;
        }
    </script>

    <!-- Vitrine - Recomendados para você -->
    <div class="widget widget-new-products">
        <div class="widget-title">
            <h2>Recomendados para você</h2>
        </div>

        <div class="widget-products">
            <ul id="recommended-showcase"
                class="products-grid products-grid--max-<?php echo $maxQtyProductsShowcase ?>-col-widget"></ul>
        </div>
    </div>

    <script src="https://cariri.prognoos.com/rec?cid=essenzedipozzi.com.br&jsonp=exibeRecsGeneral"></script>
    <script src="https://api.prognoos.com/static/vitrine.js/casadamaquina.com.br"></script>
    <script>
        var s1 = new Showcase("casadamaquina.com.br", "heu_top_category", 4, true, 1);
    </script>

<?php endif; ?>
