<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
$product = Mage::registry('current_product');
$blockInfo = $this->getData();
$maxQtyProductsShowcase = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/qty_similar_product');
$showcaseTitle = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/title_similar_product_showcase');
$prognoosHelper = Mage::helper('prognoos');
$templateEnabled = $prognoosHelper->getTemplate($blockInfo['page_name'], $blockInfo['showcase_type']);
$prognoosUser = $prognoosHelper->getPrognoosUser();
?>

<?php if ($templateEnabled): ?>
    <!-- Showcase - Similar products -->
    <div id="prognoos_lsi_showcase"></div>

    <div id="prognoos_product_style2_line" style="display:none;">
        <div class="widget widget-new-products">
            <div class="widget-title">
                <h2>##TITLE##</h2>
            </div>
            <div class="widget-products">
                <ul id="similar-product-showcase"
                    class="products-grid products-grid--max-<?php echo $maxQtyProductsShowcase ?>-col-widget">##INNER##</ul>
            </div>
        </div>
    </div>

    <div id="prognoos_product_style2" style="display:none;">
        <?php echo preg_replace('/\s+/', ' ',
            trim(Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/layout_similar_product')))?>;
    </div>
    <script>
        var extra = {
            reference: <?php echo $product->getId() ?>
        };
        PrognoosFacade.similar("<?php echo $prognoosUser ?>", <?php echo $maxQtyProductsShowcase ?>, extra);
    </script>
<?php endif; ?>
