<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
$product = Mage::registry('current_product');
$blockInfo = $this->getData();
$maxQtyProductsShowcase = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/qty_similar_product');
$showcaseTitle = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/title_similar_product_showcase');
$prognoosHelper = Mage::helper('prognoos');
$templateEnabled = $prognoosHelper->getTemplate($blockInfo['page_name'], $blockInfo['showcase_type']);
$prognoosUser = $prognoosHelper->getPrognoosUser();
?>

<?php if ($templateEnabled): ?>

    <script>

        var product_template = '<?php echo preg_replace('/\s+/', ' ',
            trim(Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/layout_similar_product')))?>';

        function exibeRecs(recommendations) {
            var di = document.getElementById('similar-product-showcase');
            var elements_html = "";

            for (var i = 0; i < <?php echo $maxQtyProductsShowcase ?>; i++) {

                var new_html = product_template.replace(/##NAME##/g, recommendations[i].name);
                new_html = new_html.replace(/##URL##/g, recommendations[i].url);
                new_html = new_html.replace(/##IMG##/g, location.protocol + recommendations[i].img_url);
                new_html = new_html.replace(/##PRICE##/g, 'R$' + recommendations[i].price);
                elements_html += new_html;
            }
            di.innerHTML = elements_html;
        }
    </script>

    <!-- Showcase - Similar products -->
    <div class="widget widget-new-products">
        <div class="widget-title">
            <h2><?php echo $showcaseTitle ?></h2>
        </div>

        <div class="widget-products">
            <ul id="similar-product-showcase"
                class="products-grid products-grid--max-<?php echo $maxQtyProductsShowcase ?>-col-widget"></ul>
        </div>
    </div>

    <!-- Getting showcase -->
    <script src="https://cariri.prognoos.com/rec?cid=<?php echo $prognoosUser ?>&lsi=<?php echo $product->getId() ?>&jsonp=exibeRecs"></script>

<?php endif; ?>
