<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
$category = Mage::registry('current_category');
$blockInfo = $this->getData();
$maxQtyProductsShowcase = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/qty_most_visited_products');
$showcaseTitle = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/title_most_visited_showcase');
$prognoosHelper = Mage::helper('prognoos');
$templateEnabled = $prognoosHelper->getTemplate($blockInfo['page_name'], $blockInfo['showcase_type']);
$prognoosUser = $prognoosHelper->getPrognoosUser();
?>

<?php if ($templateEnabled): ?>

    <script>

        var product_template = '<?php echo preg_replace('/\s+/', ' ',
            trim(Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/layout_most_visited')))?>';

        function exibeRecs(recommendations) {
            var di = document.getElementById('top-visited-showcase');
            var elements_html = "";

            for (var i = 0; i < <?php echo $maxQtyProductsShowcase ?>; i++) {

                var new_html = product_template.replace(/##NAME##/g, recommendations[i].name);
                new_html = new_html.replace(/##URL##/g, recommendations[i].url);
                new_html = new_html.replace(/##IMG##/g, location.protocol + recommendations[i].img_url);
                new_html = new_html.replace(/##PRICE##/g, 'R$' + recommendations[i].price);
                elements_html += new_html;
            }
            di.innerHTML = elements_html;
        }
    </script>

    <!-- Showcase - Top visited -->
    <div class="widget widget-new-products">
        <div class="widget-title">
            <h2><?php echo $showcaseTitle ?></h2>
        </div>

        <div class="widget-products">
            <ul id="top-visited-showcase"
                class="products-grid products-grid--max-<?php echo $maxQtyProductsShowcase ?>-col-widget"></ul>
        </div>
    </div>

    <!-- Getting showcase -->
    <script src="https://cariri.prognoos.com/heuristic?cid=<?php echo $prognoosUser ?>&heuristic=<?php echo $category->getId() ?>&jsonp=exibeRecs">
    </script>

<?php endif; ?>
