<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
$category = Mage::registry('current_category');
$blockInfo = $this->getData();
$maxQtyProductsShowcase = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/qty_most_visited_products');
$showcaseTitle = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/title_most_visited_showcase');
$prognoosHelper = Mage::helper('prognoos');
$templateEnabled = $prognoosHelper->getTemplate($blockInfo['page_name'], $blockInfo['showcase_type']);
$prognoosUser = $prognoosHelper->getPrognoosUser();
?>

<?php if ($templateEnabled): ?>
    <!-- Showcase - Top visited -->
    <div id="prognoos_heu_top_category"></div>

    <div id="prognoos_product_style3_line" style="display:none;">
        <div class="widget widget-new-products">
            <div class="widget-title">
                <h2>##TITLE##</h2>
            </div>
            <div class="widget-products">
                <ul id="top-visited-showcase"
                    class="products-grid products-grid--max-<?php echo $maxQtyProductsShowcase ?>-col-widget">##INNER##</ul>
            </div>
        </div>
    </div>
    <div id="prognoos_product_style3" style="display:none;">
        <?php echo preg_replace('/\s+/', ' ',
            trim(Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/layout_most_visited')))?>
    </div>

    <script>
    PrognoosFacade.category_popv1("<?php echo $prognoosUser ?>", <?php echo $maxQtyProductsShowcase ?>, "<?php echo $category->getId() ?>");
    </script>
<?php endif; ?>
