<?php
/**
 * @category    OmniBuy
 * @package     OmniBuy_Prognoos
 * @author      Fábio <fabio@constance.com.br>
 */
$blockInfo = $this->getData();
$maxQtyProductsShowcase = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/qty_who_bought_also_bought');
$showcaseTitle = Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/title_who_bought_also_bought_showcase');
$prognoosHelper = Mage::helper('prognoos');
$templateEnabled = $prognoosHelper->getTemplate($blockInfo['page_name'], $blockInfo['showcase_type']);
$prognoosUser = $prognoosHelper->getPrognoosUser();

$items = Mage::getModel('checkout/cart')->getQuote()->getAllItems();
$cart_top_product = reset($items);
$current_product_id = $cart_top_product->getProductId();
?>

<?php if ($templateEnabled): ?>
    <!-- Showcase - Who bought, also bought -->
    <div id="prognoos_ib_showcase"></div>
    <div id="prognoos_lsi_showcase"></div>

    <div id="prognoos_product_style2_line" style="display:none;">
        <div class="widget widget-new-products">
            <div class="widget-title">
                <h2>##TITLE##</h2>
            </div>
            <div class="widget-products">
                <ul id="who-bought-also-bought-showcase"
                    class="products-grid products-grid--max-<?php echo $maxQtyProductsShowcase ?>-col-widget">##INNER##</ul>
            </div>
        </div>
    </div>

    <div id="prognoos_product_style2" style="display:none;">
        <?php echo preg_replace('/\s+/', ' ',
            trim(Mage::getStoreConfig('vitrines/' . $blockInfo['page_name'] . '/layout_who_bought_also_bought')))?>
    </div>

    <script>
        var extra = {
            reference: <?php echo $current_product_id ?>
        };
        PrognoosFacade.ibased("<?php echo $prognoosUser ?>", <?php echo $maxQtyProductsShowcase ?>, extra);
        PrognoosFacade.similar("<?php echo $prognoosUser ?>", <?php echo $maxQtyProductsShowcase ?>, extra);
    </script>


<?php endif; ?>
